### ISSUE TITLE
#120 still an issue. 

### ISSUE THREAD

**Issue by toqduj** [sailoog/openplotter#138]
The security issue from #120 still exists in the latest v0.9.0. Also, perhaps this can be side-stepped. I noticed that Raspbian Jessie now comes with a licensed VNC client already installed, which, if I'm not misled by another installation, uses an encrypted connection. This means that Openplotter doesn't need to install this anymore, just switch it on.

**Comment by sailoog** [comment]
Reopening https://github.com/sailoog/openplotter/issues/120 and closing this one.
