### ISSUE TITLE
Error when starting SDR

### ISSUE THREAD

**Issue by syska** [sailoog/openplotter#158]
I get this error when starting SDR from the command line (the shortcut does not work)

I'm not sure how much more information you need. 

I have no expirience with python.

Here is what I get:
pi@openplotter:~/.config/openplotter/tools $ python SDR_AIS.py 
Traceback (most recent call last):
  File "SDR_AIS.py", line 235, in <module>
    MyFrame().Show()
  File "SDR_AIS.py", line 111, in __init__
    self.button_vhf_Tx.Disable()
AttributeError: 'MyFrame' object has no attribute 'button_vhf_Tx'

Python is version 2.7.9

**Comment by sailoog** [comment]
What is your openplotter version?

**Comment by syska** [comment]
0.9.0alpha ...

I guess I should try to update ... Let me see if I can figure out how to do that 😀

**Comment by syska** [comment]
So this fixed the issue. Next issue.
