### ISSUE TITLE
Units for MWV sentence

### ISSUE THREAD

**Issue by tiziana31** [sailoog/openplotter#163]
Is there a possibility to use other units (e.g knots) as input sentence for the windmeter of intrumentenpanel?
As I understood the spec it's possible to have units of K/M/N
An example of my Nexus NX2 server is:
$IIMWV,338,R,16.36,N,A*29

Regards

**Comment by e-sailing** [comment]
Instrumentpanel is part of signalk. Signalk converts everything into si unit. So it doesn't matter if you put in a nmea0183 sentence in K/M/N. It will be converted to si unit. But the displayed unit can be set in instrumentpanel. You can play with instrumentpanel settings at URL:http://signalk.org/demo.html.
