### ISSUE TITLE
RDP remote desktop not working

### ISSUE THREAD

**Issue by torgeirnag** [sailoog/openplotter#166]
In order to get RDP working I have to run:
`sudo apt-get install vnc4server`

https://raspberrypi.stackexchange.com/questions/56413/error-problem-connecting-to-raspberry-pi-3-with-xrdp

**Comment by sailoog** [comment]
Yes, we are considering removing VNC server from the default image which has conflict with RDP. We are using x11vnc on openplotter but you can use another one if you want
