### ISSUE TITLE
NOOBS don't see the OS 

### ISSUE THREAD

**Issue by border0464111** [sailoog/openplotter#178]
Hi I tried to download the zipfile from github and install it on my SD card, the NOOBS install menu open but there is no OS to install. 

I downloaded and uploaded on my SD card the last version of NOOBS and add openplotter into the OS folder. When I boot my raspberry, I see and can install others OS but not openplotter. 

Note that I have a raspberryB (the second generation )  

What Can I do, to investigate further ?

**Comment by toqduj** [comment]
If you want to install the dev version, start from this image, and, once installed, update the OS and update OP. Both can be done in the openplotter interface. 
http://sailoog.com/en/blog/download-openplotter-rpi-v0100-noobs

**Comment by sailoog** [comment]
OpenPlotter NOOBS is not raspberry 1 compatible, only raspberry 2 and 3.
