### ISSUE TITLE
Include Avahi for Signal K discovery

### ISSUE THREAD

**Issue by tkurki** [sailoog/openplotter#180]
Apparently the current setup does not include Avahi (os level support) and Mdns (Signal K server level support). They are needed for Signal K client apps to autodiscover the server.

https://github.com/sailoog/openplotter/issues/170#issuecomment-326791835

**Comment by sailoog** [comment]
OK. I remember that being on the to do list, what I can not remember is why this jumped. I will check if there is any incompatibility with the current Wifi AP management. Thanks.

@tkurki can I have your email? I have some questions about SK server. Mine is info[youknowwhat]sailoog.com

**Comment by toqduj** [comment]
On my test system running the latest OP beta, it shows no obvious problem. Both with bridged eth0 and without, the AP section and functionality works fine. With avahi and mdns installed.

**Comment by sailoog** [comment]
I will add this to the next major update. Did it need any extra configuration or just installing?

@tkurki we are close to the stable version and waiting for this to make a major update: https://github.com/SignalK/specification/issues/244 any news?

**Comment by tkurki** [comment]
No configuration needed, Node server just checks if npm module `mdns` is available, which in turn needs avahi.

**Comment by tkurki** [comment]
As for enums let's continue discussion at https://github.com/SignalK/specification/pull/382.

**Comment by sailoog** [comment]
FYI

node v6.11.4
signalk-server-node 0.1.32

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**Comment by tkurki** [comment]
This is normal.

**Comment by tkurki** [comment]
Do you install SK server from npm?

**Comment by sailoog** [comment]
Yes

**Comment by tkurki** [comment]
All right, I’ll pay more attention to publishing there. So far I have assumed that most people install from Github, that’s why I asked.

**Comment by sailoog** [comment]
ops sorry I misunderstood the question. I use github.
