### ISSUE TITLE
MPU-9150 IMU lag/delay

### ISSUE THREAD

**Issue by denhamt** [sailoog/openplotter#193]
Just hooked up a new MPU-9150 to a fresh RPi3 and clean install updated to OP 0.17.0.

I'm seeing a lag/delay of the IMU readings of about 5 seconds. I'm working to read the raw data to confirm which side the issue is on. Any other reports of this or advise?

**Comment by davewinwood** [comment]
I have exactly the same problem on a fresh install and MPU - massive lag in data of around 5 seconds. Tried calibrating several times but all MPU data is very delayed. Did you get a fix?

**Comment by sailoog** [comment]
old issue. New versions of OP use new calibration methods, reopen a new issue if you need.
