### ISSUE TITLE
"Publish to MQTT" missing from Add Action menu.

### ISSUE THREAD

**Issue by denhamt** [sailoog/openplotter#194]
Version 0.17.0

Followed this thread closely to setup remote MQTT. It seems the "Publish to MQTT" action is missing from the drop down menu. Publish Twitter is the only Publish command found there. (Yes I scrolled down the drop down menu)

Can anyone else confirm? Is there another way to send SK keys to MQTT?

![image](https://user-images.githubusercontent.com/32051173/35715517-bc99b1e8-0787-11e8-8c66-d388ccfa0d86.png)

**Comment by jamesewilliamson** [comment]
i pull them off the websocket in node-red and then publish them with a mqtt out node

**Comment by sailoog** [comment]
MQTT has been rebuilt. closing this issue, open a new one if you need.
