### ISSUE TITLE
Can't open openplotter

### ISSUE THREAD

**Issue by vincenthure** [sailoog/openplotter#195]
I get this message and don't understand why

./openplotter.py
Traceback (most recent call last):
  File "./openplotter.py", line 2906, in <module>
    MainFrame().Show()
  File "./openplotter.py", line 660, in __init__
    self.set_layout_conf()
  File "./openplotter.py", line 808, in set_layout_conf
    with open(home+'/.config/signalk-server-node/settings/openplotter-settings.json') as data_file:
IOError: [Errno 2] No such file or directory: '/home/pi/.config/signalk-server-node/settings/openplotter-settings.json'

**Comment by vincenthure** [comment]
When I make a fresh install on RPI it was working well
After one day it was broken. I suppose that the file "openplotter-settings.json" disappear.
who can I regenerate it?

**Comment by e-sailing** [comment]
You are using an old version 0.8 I think. There isn't any file openplotter.py today it is simply openplotter

**Comment by thezerocool** [comment]
probably the same issue I am having, I posted a seperate issue as my error is different but the cause of my signalk error was an update from a old version, 1.0 im guessing, to 1.2
