### ISSUE TITLE
Signal K

### ISSUE THREAD

**Issue by joabakk** [sailoog/openplotter#22]
Hi again,

Openplotter is my first experience with Signal K, so excuse me if I get this all wrong, but are the openplotter generated nmea strings showing up in the instrument panel page? I got it working once with data, but I believe that was when I had my dummy nmea generator connected. I would expect that at least the hdm should show now that I have an IMU hooked up.

**Comment by sailoog** [comment]
I am afraid Signal k and instrument panel are in earlier beta stage and there are some NMEA 0183 sentences not implemented yet. I can remember hdm does not have panel yet. If you want to test the panel instrument with all of its features, you had better test remotely from the browser of a computer connected to OpenPlotter as access point or in the same network, it is promising...
