### ISSUE TITLE
Can't connect over Wi-FI using SSH or RDP

### ISSUE THREAD

**Issue by Phil-Taylor-IW** [sailoog/openplotter#228]
Hi there, I just booted openplotter_v1.0.0_img off the SD card in my Pi 3 Model B+

I can connect to the SSID: openplotter, get an IP address and ping 10.10.10.1 OK but a port scan shows no open ports on tcp/22 SSH or RDP so the MacBook fails to connect. Same result on ethernet using the IP from the router's DHCP or openplotter.local. A VNC connection using the native Mac client says the software is out of date so will try another VNC client and advise.

```
Starting Nmap 7.40 ( https://nmap.org ) at 2018-12-10 14:29 NZDT
Nmap scan report for openplotter.local (172.17.12.176)
Host is up (0.0046s latency).
Other addresses for openplotter.local (not scanned): fd00::ba27:ebff:fec4:b274
Not shown: 997 closed ports
PORT     STATE SERVICE
53/tcp   open  domain
3000/tcp open  ppp
5900/tcp open  vnc

Nmap done: 1 IP address (1 host up) scanned in 7.12 seconds
```

Looks like a great product so could someone please assist?

Thanks, Phil

PS I would have asked in the forum but my registration confirmation email hasn't arrived

PPS Have emailed Sean as well

**Comment by andyrbarrow** [comment]
Have you checked the Raspberry Pi configuration, or from a terminal session, raspi-config. Connect via VNC and check that SSH is enabled.

**Comment by Phil-Taylor-IW** [comment]
I’m in now via VNC Viewer and can confirm the SSH server is disabled so perhaps you need to update your documentation?

Thanks

**Comment by Phil-Taylor-IW** [comment]
It's disabled but your documentation say that VNC, RDP and SSH are the options?

**Comment by sailoog** [comment]
You are reading documentation for v0.1.x
https://sailoog.gitbooks.io/openplotter-documentation/content/en/

You need to follow docs for v1.x.x
https://docs.sailoog.com/openplotter-v1-x-x/
