### ISSUE TITLE
Signal K: upgrade required

### ISSUE THREAD

**Issue by joabakk** [sailoog/openplotter#23]
Hm, when I try to connect to localhost:3000/signalk/api/v1 and so on, the webpage just says "upgrade required". But I find no reference to how to do that on the signal K pages in git or org. Does anyone have a clue?

**Comment by sailoog** [comment]
localhost:3000/signalk/api/v1 is a websocket so as far as I know you can not connect to it from the browser directly. Here you have an example of connection to websocket
https://github.com/SignalK/signalk-server-node/blob/master/examples/consumer-example.html
