### ISSUE TITLE
where is install-wifi ? 

### ISSUE THREAD

**Issue by FredericGuilbault** [sailoog/openplotter#257]
In `openplotter/classes/install-wifi.sh` is calling `sudo install-wifi` but I don't get where this file should be comming from.

**Comment by sailoog** [comment]
https://github.com/sailoog/openplotter/blob/bcefaf58b07c1f52e384c6d82fda72750f10ac11/update/update_dependencies.sh#L158

**Comment by FredericGuilbault** [comment]
thx
