### ISSUE TITLE
big upgrade has broken system  0.10 to 0.17

### ISSUE THREAD

**Issue by jellmers** [sailoog/openplotter#271]
So I installed OpenPlotter last year on the boat and everything was working great.

RasPi3 with the Official Touchscreen (v0.10 was what was working)

Brought the system back home at the weekend, and decided to plug it in and go through what I knew would be a significant upgrade.....
It was and it broke it all.... :-)

I am getting a dialogue up now when running OpenPlotter that says that signalK server was unable to start......  I have looked through the forums and tried to manually upgrade the signalk-server-node.  But it is still happening.......

Any ideas?

I also have an issue with the new version on OpenCPN (5.0) whereby I cant touch the settings button to open it....  Any ideas on that one???

Kind regards

**Comment by sailoog** [comment]
I am afraid v0.10 is too old an will never work with opencpn 5 and the current signal k version. SK depends on node 11 and v0.10 has node 8. I can not remeber the opencpn dependencies but is the same case. You have to download and install openplotter 1.x or wait for openplotter 2.x which is in beta stage.
