### ISSUE TITLE
Fails to install some apps

### ISSUE THREAD

**Issue by pcav** [sailoog/openplotter#273]
I successfully installed 2.0.18-beta in my Debian Sid box. All fine, I update sources, installed settings and docs, but when I ask to install OpenCPN or tools panel nothing happens.
Sorry if this is misplaced, please let me know if I should write to the forum instead.
Thanks.

**Comment by pcav** [comment]
After that the application hungs, and I have to manually kill it.

**Comment by sailoog** [comment]
This openplotter repo is dead. You should use forum.openmarine.net or this repo: https://github.com/openplotter/openplotter-settings

Open a terminal, run "openplotter-settings", play with features and report any error in terminal.

We have never tested with Sid, just stable versions.

**Comment by pcav** [comment]
This is what I did. I'll report in the other repo.
Thanks.
