### ISSUE TITLE
IMU settings to reset orientation

### ISSUE THREAD

**Issue by joabakk** [sailoog/openplotter#28]
as mentioned in the closed issue, it would be good to be able to align the orientation after the imu has been mounted. We could take a gps fix on the bow, walk a few hundred meters and take a new fix to get an exact boat heading, walk back and add or subtract the difference in heading between gps and compass. Also, the roll /heel may be corrected when the boat is level.

**Comment by sailoog** [comment]
I have made some improvements and debug in IMU code which I would want to test in the next release. If we get good feedbacks I will implement this "reset" feature you suggest.

**Comment by joabakk** [comment]
I have tried to pull your code and test it, but I can no longer open openplotter.py from the start screen. No Idea what happened

**Comment by sailoog** [comment]
Install https://github.com/timofurrer/w1thermsensor

**Comment by joabakk** [comment]
Thanks, that worked. But maybe it's n idea to test the presence of this library in the code, instead of crashing? This means it's no longer a git clone of this repo.
