### ISSUE TITLE
Multipe Acces VNC

### ISSUE THREAD

**Issue by hwater** [sailoog/openplotter#43]
Add Multple Access & Use Password to VNC in File startup.py

#	subprocess.Popen(['x11vnc', '-forever'])     
	subprocess.Popen(['x11vnc', '-usepw', '-forever', '-shared'])

**Comment by sailoog** [comment]
I agree with -shared but we should implement some way to set the password, any idea?

**Comment by hwater** [comment]
About the password:

i would not go too far into the system - some Dokumentation should be enough.
Most People only set it one Time….

Keep on with your great Work

Holger Watermann

> Am 02.03.2016 um 11:52 schrieb Sailoog <notifications@github.com>:
> 
> I agree with -shared but we should implement some way to set the password, any idea?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/sailoog/openplotter/issues/43#issuecomment-191185547>.
> 

—  
Holger Watermann
Administrator
Information Management

JOHANNES KEPLER
UNIVERSITY LINZ
Altenberger Strasse 69
Hochschulfond Building, HF9903
4040 Linz, Austria
P +43 732 2468 3927
holger.watermann@jku.at <mailto:holger.watermann@jku.at>
www.jku.at/im <http://www.jku.at/im>

**Comment by e-sailing** [comment]
I use xrdp. I can open more desktops on different clients with the same username.
I don't know if it is the better solution.

Martin

**Comment by sailoog** [comment]
It's better for me too but  VNC is most popular

**Comment by hwater** [comment]
Hello sailoog

please add the two optional checkboxes for VNC enabler in the Startup Page.
x "enable Multiuser" ('-shared')
x "use Password" ('-usepw')

thx (i have to edit them in after every clone for using "ScreenSharing" in MacOS X) 
or make them into one Checkbox called "MacOS X compatible"

**Comment by sailoog** [comment]
I was delaying this suggestion because I didn't know how to deal with the password but I have an idea now, let me try...

**Comment by sailoog** [comment]
Done. It will be always shared and password optional. Test and confirm please.

**Comment by hwater** [comment]
Well done, works here. One Quirk, if you check the Passwd-Box for second Time, it should give you an Requester "Do you really want to change your VNC-Passwd ?" with "Cancel" & "Okay" before opening the Terminal.

Oherwise well done!

**Comment by sailoog** [comment]
Done, well, something similar :) the requester will run always. Thanks.
