### ISSUE TITLE
node-red

### ISSUE THREAD

**Issue by eggersd** [sailoog/openplotter#46]
Is it reasonable to run node-red (which required node.js and npm) at the same time as the open-plotter applications?  I tried on v0.6.0beta unsuccessfully.

**Comment by eggersd** [comment]
has anyone else been able to install and run node-red with open plotter?  I tried a while back and it seemed to conflict with open plotter.

**Comment by sailoog** [comment]
Sorry no experience with node-red here. What kind of conflict are you getting?

**Comment by sailoog** [comment]
v0.9.0alpha implements node-red
