### ISSUE TITLE
RTIMULib´s missing in latest clone?

### ISSUE THREAD

**Issue by hwater** [sailoog/openplotter#49]
Hello

just did an full clone, is it true - these files are missing
-rw-r--r-- 1 pi pi 12083 Mär 14 16:55 RTIMULib2.ini
-rw-r--r-- 1 pi pi 12083 Mär 14 16:55 RTIMULib3.ini
-rw-r--r-- 1 pi pi 12083 Mär 14 16:55 RTIMULib.ini

Or are they generated on the Fly? Just wondering as i cant test now on pi ....

**Comment by sailoog** [comment]
They are generated on the Fly when a sensor is detected. when you press "reset" in I2C sensors tab, they are deleted and generated again.
