### ISSUE TITLE
Desktop screen size, not full screen

### ISSUE THREAD

**Issue by Nick-Currawong** [sailoog/openplotter#57]
Hello,
I have a issue with the screen size, I can't get mine to expand to the full screen, 
![img_0515](https://cloud.githubusercontent.com/assets/17544217/14132902/dcada908-f64a-11e5-95ca-ee8e46a594ee.JPG)
I have tried various setting within the config.txt.
I have other pi images which do use the full screen , I have tried their settings. All without any luck.

The screen is a Makibes 7 inch LCD.

I don't expect this is a issue with openplotter but I can't find anything on the net which seems to help.

Thanks
Nick

**Comment by sailoog** [comment]
I read on cruisersforum that you fixed this :) Closing...
