### ISSUE TITLE
True wind not calculated when SOG = 0.0 ?

### ISSUE THREAD

**Issue by LeaseOnLife** [sailoog/openplotter#95]
I selected "GPS speed" to calculate true wind. It seems true wind needs a SOG >0.0 to perform a calculation.I am plotting/watching true windspeed and wind angle at anchor and I only seem to get updates when the boat moves.  This isn't right, at SOG=0.0 ==> TWA = AWA and TWS = AWS. 

Dirk

**Comment by sailoog** [comment]
You are right, some users also reprted this. It will be fixed on next releases. Thanks!!

**Comment by sailoog** [comment]
fixed on v0.17.0
