### ISSUE TITLE
graph.py: please add true wind direction and true wind speed 

### ISSUE THREAD

**Issue by LeaseOnLife** [sailoog/openplotter#99]
To watch trends, besides the barometric pressure, it would be great to also have true wind direction (in reference to North, not to the bow of the boat) and true wind speed to plot in graph.py.

Thanks

Dirk

**Comment by sailoog** [comment]
We have plans to replace graph.py in v 0.9.0 by some custom dashboard to show current values, historic and trends of any Signal K value. Actually you could do this on v0.8.0 sending wind values through MQTT to some app to build graphs.
